# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:18
from __future__ import unicode_literals

import common.utils
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion

from unipath import Path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location=Path('./public/media/images')), upload_to=common.utils.image_path, verbose_name='Article image')),
                ('text', models.TextField(verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified date time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
